# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: React Native SSL WebSocket Package

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      #- run: npm install --omit=dev --legacy-peer-deps --ignore-scripts
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --legacy-peer-deps
      - run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-native-ssl-websocket
          path: |
            ./dist/*
            ./src/*
            ./android/*
            ./ios/*
            ./*.podspec
            ./codegen.json
            ./package.json
            ./README.md
            ./LICENSE
            ./tsconfig*.json
            ./babel.config.js

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-native-ssl-websocket
          path: .

      - name: Publish to NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
